"""add cash to user

Revision ID: 67900a207d0d
Revises: f4e2b09b8258
Create Date: 2020-07-11 20:14:10.221401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67900a207d0d'
down_revision = 'f4e2b09b8258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cash', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cash')
    # ### end Alembic commands ###
